version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: ./compose/django-compose/Dockerfile
    image: image_backend_khasan
    restart: always
    command: /start
    volumes:
      - .:/app
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - "8077:8077"
    env_file:
      - .env
    depends_on:
      - db

  nginx:
    build:
      context: .
      dockerfile: compose/nginx/Dockerfile
    depends_on:
      - backend

  db:
    image: postgres:alpine
    container_name: postgres_khasan
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: always
    environment:
      - POSTGRES_PASSWORD=1
      - POSTGRES_DB =test

  minio:
    image: minio/minio
    ports:
      - "9006:9006"
      - "9007:9007"
    environment:
      MINIO_ROOT_USER: user
      MINIO_ROOT_PASSWORD: password
    volumes:
      - minio_storage:/data
    command: server --address ":9006" --console-address ":9007" /data
    restart: always


volumes:
  postgres_data:
  minio_storage:
  static_volume:
  media_volume: