version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: ./compose/django-compose/Dockerfile
    container_name: backend_khasan
    image: image_backend_khasan
    restart: always
    command: /start
    volumes:
      - .:/app
    ports:
      - "8077:8077"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:alpine
    container_name: postgres_khasan
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: always
    environment:
      - POSTGRES_PASSWORD=1
      - POSTGRES_USER=postgres
      - POSTGRES_DB=test
    ports:
      - "5432:5432"

  #  minio:
  #    image: bitnami/minio
  #    container_name: minio_khasan
  #    ports:
  #      - "9006:9006"
  #      - "9007:9007"
  #    volumes:
  #      - minio_storage:/data
  #    environment:
  #      MINIO_ROOT_USER: user
  #      MINIO_ROOT_PASSWORD: password
  #    command: server --console-address ":9007" /data
  #

  minio:
    image: minio/minio
    ports:
      - "9006:9006"
      - "9007:9007"
    environment:
      MINIO_ROOT_USER: user
      MINIO_ROOT_PASSWORD: password
    volumes:
      - minio_storage:/data
    command: server --address ":9006" --console-address ":9007" /data
    restart: always # necessary since it's failing to start sometimes


volumes:
  postgres_data:
  minio_storage: